### PR TITLE
github actions bot should sign his commits

### PR DESCRIPTION
**Pull request by vsoch**
This technique usually satisfies the DCO bot, we will see if it satisfies the branch protection rules too!

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
I'm also thinking we shouldn't need to wait for a build given no changes to packages - don't review/approve here yet I'm going to add a check for changed files.

**Comment by vsoch** [comment]
okay that's better :)

**Review by grondo — APPROVED** [review]
In case you need a review: LGTM! Thanks!

**Comment by grondo** [comment]
I wonder if the rule GitHub is complaining about signing commits, vs "signing off" on commits. Needs more research. I still don't see how that requirement was enabled though...

**Comment by vsoch** [comment]
We will see for the next time there is a flux release and the bot opens a PR! I'm not sure either.

**Comment by grondo** [comment]
Ok, the setting was under branch protection rules. I've disabled it for now b/c I don't think we'll be able to get a bot to sign commits, bit we can always reenable it if we figure it out!

**Comment by vsoch** [comment]
I actually got this working for oras-www -> https://github.com/oras-project/oras-www/pull/32/commits/4333a90ab20a28cbd23ddf2f6d538efbeded7989. So I'll check for the next one, and if it works we can turn it back on. It's probably overkill but I like it as a general practice.

**Pull request merged**
